package mysql

var sqliteColumnMigrations = []columnMigration{
	{Table: "users", Column: "aff_balance_cents", Definition: "INTEGER NOT NULL DEFAULT 0"},
	{Table: "users", Column: "plan_id", Definition: "INTEGER NULL"},
	{Table: "users", Column: "user_group_id", Definition: "INTEGER NULL"},
	{Table: "users", Column: "max_rules", Definition: "INTEGER NOT NULL DEFAULT 0"},
	{Table: "users", Column: "traffic_enable", Definition: "INTEGER NOT NULL DEFAULT 1"},
	{Table: "users", Column: "auto_renew", Definition: "INTEGER NOT NULL DEFAULT 0"},
	{Table: "users", Column: "telegram_id", Definition: "TEXT NOT NULL DEFAULT ''"},
	{Table: "users", Column: "invite_code", Definition: "TEXT NOT NULL DEFAULT ''"},
	{Table: "users", Column: "invited_by_user_id", Definition: "INTEGER NULL"},
	{Table: "users", Column: "allow_device", Definition: "INTEGER NOT NULL DEFAULT 1"},
	{Table: "users", Column: "notification_settings_json", Definition: "TEXT NULL"},
	{Table: "tunnels", Column: "listen_port", Definition: "INTEGER NULL"},
	{Table: "tunnels", Column: "listen_host", Definition: "TEXT NOT NULL DEFAULT ''"},
	{Table: "tunnels", Column: "target_host", Definition: "TEXT NOT NULL DEFAULT ''"},
	{Table: "tunnels", Column: "target_port", Definition: "INTEGER NULL"},
	{Table: "tunnels", Column: "device_group_in_id", Definition: "INTEGER NULL"},
	{Table: "tunnels", Column: "device_group_out_id", Definition: "INTEGER NULL"},
	{Table: "tunnels", Column: "config_json", Definition: "TEXT NULL"},
	{Table: "tunnels", Column: "folder", Definition: "TEXT NOT NULL DEFAULT ''"},
	{Table: "tunnels", Column: "show_order", Definition: "INTEGER NOT NULL DEFAULT 0"},
	{Table: "tunnels", Column: "traffic_reset_at", Definition: "DATETIME NULL"},
	{Table: "forward_services", Column: "config_json", Definition: "TEXT NULL"},
	{Table: "forward_services", Column: "device_group_in_id", Definition: "INTEGER NULL"},
	{Table: "forward_services", Column: "device_group_out_id", Definition: "INTEGER NULL"},
	{Table: "forward_services", Column: "listen_port", Definition: "INTEGER NULL"},
	{Table: "forward_services", Column: "last_report_at", Definition: "DATETIME NULL"},
	{Table: "payment_orders", Column: "type", Definition: "TEXT NOT NULL DEFAULT 'deposit'"},
	{Table: "payment_orders", Column: "plan_id", Definition: "INTEGER NULL"},
	{Table: "payment_orders", Column: "quantity", Definition: "INTEGER NOT NULL DEFAULT 1"},
	{Table: "payment_orders", Column: "metadata_json", Definition: "TEXT NULL"},
	{Table: "payment_orders", Column: "expired_at", Definition: "DATETIME NULL"},
	{Table: "payment_orders", Column: "closed_at", Definition: "DATETIME NULL"},
}
