package mysql

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS admins (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		username VARCHAR(64) NOT NULL UNIQUE,
		password_hash VARCHAR(255) NOT NULL,
		status VARCHAR(16) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS users (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		username VARCHAR(64) NOT NULL UNIQUE,
		password_hash VARCHAR(255) NOT NULL,
		status VARCHAR(16) NOT NULL,
		balance_cents BIGINT NOT NULL DEFAULT 0,
		flow_quota_mb BIGINT NOT NULL DEFAULT 0,
		traffic_used_bytes BIGINT NOT NULL DEFAULT 0,
		expires_at DATETIME(6) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS nodes (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(128) NOT NULL UNIQUE,
		host VARCHAR(255) NOT NULL,
		port INT NOT NULL,
		secret VARCHAR(255) NOT NULL,
		status VARCHAR(16) NOT NULL,
		last_seen_at DATETIME(6) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS tunnels (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		user_id BIGINT NOT NULL,
		node_id BIGINT NOT NULL,
		name VARCHAR(128) NOT NULL,
		protocol VARCHAR(8) NOT NULL,
		listen_addr VARCHAR(255) NOT NULL,
		target_addr VARCHAR(255) NOT NULL,
		max_conn INT NOT NULL DEFAULT 0,
		speed_limit_kb INT NOT NULL DEFAULT 0,
		quota_bytes BIGINT NOT NULL DEFAULT 0,
		used_bytes BIGINT NOT NULL DEFAULT 0,
		expires_at DATETIME(6) NULL,
		auto_pause_on_limit TINYINT(1) NOT NULL DEFAULT 1,
		status VARCHAR(16) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		INDEX idx_tunnels_user_id (user_id),
		INDEX idx_tunnels_node_id (node_id),
		CONSTRAINT fk_tunnels_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
		CONSTRAINT fk_tunnels_node_id FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS forward_services (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		tunnel_id BIGINT NOT NULL UNIQUE,
		user_id BIGINT NOT NULL,
		node_id BIGINT NOT NULL,
		service_key VARCHAR(128) NOT NULL UNIQUE,
		protocol VARCHAR(8) NOT NULL,
		listen_addr VARCHAR(255) NOT NULL,
		target_addr VARCHAR(255) NOT NULL,
		status VARCHAR(16) NOT NULL,
		max_conn INT NOT NULL DEFAULT 0,
		speed_limit_kb INT NOT NULL DEFAULT 0,
		quota_bytes BIGINT NOT NULL DEFAULT 0,
		used_bytes BIGINT NOT NULL DEFAULT 0,
		bytes_in BIGINT NOT NULL DEFAULT 0,
		bytes_out BIGINT NOT NULL DEFAULT 0,
		active_conn INT NOT NULL DEFAULT 0,
		paused_reason VARCHAR(255) NOT NULL DEFAULT '',
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		INDEX idx_forward_services_node_id (node_id),
		INDEX idx_forward_services_user_id (user_id),
		CONSTRAINT fk_forward_services_tunnel_id FOREIGN KEY (tunnel_id) REFERENCES tunnels(id) ON DELETE CASCADE,
		CONSTRAINT fk_forward_services_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
		CONSTRAINT fk_forward_services_node_id FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS payment_channels (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		code VARCHAR(64) NOT NULL UNIQUE,
		name VARCHAR(128) NOT NULL,
		enabled TINYINT(1) NOT NULL DEFAULT 1,
		provider VARCHAR(32) NOT NULL,
		config_json JSON NOT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS payment_orders (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		order_no VARCHAR(64) NOT NULL UNIQUE,
		user_id BIGINT NOT NULL,
		channel VARCHAR(64) NOT NULL,
		amount_cents BIGINT NOT NULL,
		status VARCHAR(16) NOT NULL,
		pay_url VARCHAR(1024) NOT NULL DEFAULT '',
		trade_no VARCHAR(128) NOT NULL DEFAULT '',
		raw_request LONGTEXT NOT NULL,
		raw_notify LONGTEXT NOT NULL,
		paid_at DATETIME(6) NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		INDEX idx_payment_orders_user_id (user_id),
		INDEX idx_payment_orders_status (status),
		CONSTRAINT fk_payment_orders_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS sessions (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		actor_kind VARCHAR(16) NOT NULL,
		actor_id BIGINT NOT NULL,
		token_hash VARCHAR(128) NOT NULL UNIQUE,
		expires_at DATETIME(6) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		INDEX idx_sessions_actor (actor_kind, actor_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS node_commands (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		node_id BIGINT NOT NULL,
		type VARCHAR(32) NOT NULL,
		payload_json JSON NOT NULL,
		status VARCHAR(16) NOT NULL,
		available_at DATETIME(6) NOT NULL,
		consumed_at DATETIME(6) NULL,
		created_at DATETIME(6) NOT NULL,
		INDEX idx_node_commands_node_status_id (node_id, status, id),
		CONSTRAINT fk_node_commands_node_id FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS usage_reports (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		node_id BIGINT NOT NULL,
		service_key VARCHAR(128) NOT NULL,
		bytes_in BIGINT NOT NULL,
		bytes_out BIGINT NOT NULL,
		active_conn INT NOT NULL,
		reported_at DATETIME(6) NOT NULL,
		created_at DATETIME(6) NOT NULL,
		INDEX idx_usage_reports_node_id (node_id),
		INDEX idx_usage_reports_service_key (service_key),
		CONSTRAINT fk_usage_reports_node_id FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS audit_logs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		actor_kind VARCHAR(16) NOT NULL,
		actor_id BIGINT NOT NULL,
		action VARCHAR(64) NOT NULL,
		target_kind VARCHAR(64) NOT NULL,
		target_id BIGINT NOT NULL DEFAULT 0,
		detail_json LONGTEXT NOT NULL,
		created_at DATETIME(6) NOT NULL,
		INDEX idx_audit_logs_actor (actor_kind, actor_id),
		INDEX idx_audit_logs_action (action)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
}

var migrationStatements = []string{
	`CREATE TABLE IF NOT EXISTS schema_migrations (
		version VARCHAR(64) PRIMARY KEY,
		description VARCHAR(255) NOT NULL,
		applied_at DATETIME(6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS device_groups (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(128) NOT NULL,
		type VARCHAR(32) NOT NULL DEFAULT 'node',
		node_id BIGINT NULL,
		ratio DECIMAL(10,4) NOT NULL DEFAULT 1.0000,
		connect_host VARCHAR(255) NOT NULL DEFAULT '',
		port_range_start INT NULL,
		port_range_end INT NULL,
		config_json JSON NULL,
		show_order INT NOT NULL DEFAULT 0,
		display_num INT NOT NULL DEFAULT 0,
		hide_status TINYINT(1) NOT NULL DEFAULT 0,
		status VARCHAR(16) NOT NULL DEFAULT 'enabled',
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		deleted_at DATETIME(6) NULL,
		INDEX idx_device_groups_type (type),
		INDEX idx_device_groups_node_id (node_id),
		INDEX idx_device_groups_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS plans (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(128) NOT NULL,
		description TEXT NULL,
		price_cents BIGINT NOT NULL DEFAULT 0,
		traffic_mb BIGINT NOT NULL DEFAULT 0,
		duration_days INT NOT NULL DEFAULT 0,
		max_rules INT NOT NULL DEFAULT 0,
		allow_device TINYINT(1) NOT NULL DEFAULT 1,
		user_group_id BIGINT NULL,
		status VARCHAR(16) NOT NULL DEFAULT 'enabled',
		show_order INT NOT NULL DEFAULT 0,
		config_json JSON NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		deleted_at DATETIME(6) NULL,
		INDEX idx_plans_status (status),
		INDEX idx_plans_show_order (show_order)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS user_groups (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		name VARCHAR(128) NOT NULL,
		description TEXT NULL,
		max_rules INT NOT NULL DEFAULT 0,
		traffic_multiplier DECIMAL(10,4) NOT NULL DEFAULT 1.0000,
		permissions_json JSON NULL,
		show_order INT NOT NULL DEFAULT 0,
		status VARCHAR(16) NOT NULL DEFAULT 'enabled',
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		INDEX idx_user_groups_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS redeem_codes (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		code VARCHAR(64) NOT NULL UNIQUE,
		type VARCHAR(32) NOT NULL DEFAULT 'balance',
		amount_cents BIGINT NOT NULL DEFAULT 0,
		plan_id BIGINT NULL,
		traffic_mb BIGINT NOT NULL DEFAULT 0,
		duration_days INT NOT NULL DEFAULT 0,
		max_use INT NOT NULL DEFAULT 1,
		used_count INT NOT NULL DEFAULT 0,
		status VARCHAR(16) NOT NULL DEFAULT 'enabled',
		expires_at DATETIME(6) NULL,
		created_by_admin_id BIGINT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL,
		INDEX idx_redeem_codes_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS redeem_logs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		redeem_code_id BIGINT NOT NULL,
		user_id BIGINT NOT NULL,
		order_id BIGINT NULL,
		created_at DATETIME(6) NOT NULL,
		UNIQUE KEY uniq_redeem_user_code (redeem_code_id, user_id)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS aff_logs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		user_id BIGINT NOT NULL,
		from_user_id BIGINT NULL,
		order_id BIGINT NULL,
		type VARCHAR(32) NOT NULL,
		amount_cents BIGINT NOT NULL DEFAULT 0,
		rate DECIMAL(10,4) NOT NULL DEFAULT 0,
		status VARCHAR(16) NOT NULL DEFAULT 'pending',
		detail_json JSON NULL,
		created_at DATETIME(6) NOT NULL,
		accounted_at DATETIME(6) NULL,
		INDEX idx_aff_logs_user_id (user_id),
		INDEX idx_aff_logs_status (status)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS system_kv (
		key_name VARCHAR(128) PRIMARY KEY,
		value_json JSON NULL,
		value_text LONGTEXT NULL,
		scope VARCHAR(32) NOT NULL DEFAULT 'global',
		updated_by_admin_id BIGINT NULL,
		created_at DATETIME(6) NOT NULL,
		updated_at DATETIME(6) NOT NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`CREATE TABLE IF NOT EXISTS notification_logs (
		id BIGINT PRIMARY KEY AUTO_INCREMENT,
		user_id BIGINT NULL,
		channel VARCHAR(32) NOT NULL,
		type VARCHAR(64) NOT NULL,
		title VARCHAR(255) NOT NULL DEFAULT '',
		content TEXT NULL,
		status VARCHAR(16) NOT NULL DEFAULT 'pending',
		raw_response TEXT NULL,
		created_at DATETIME(6) NOT NULL,
		sent_at DATETIME(6) NULL
	) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
	`INSERT IGNORE INTO device_groups(name, type, node_id, connect_host, status, created_at, updated_at)
		SELECT name, 'node', id, host, 'enabled', created_at, updated_at FROM nodes`,
}
