package mysql

var sqliteSchemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS admins (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT NOT NULL UNIQUE,
		password_hash TEXT NOT NULL,
		status TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		username TEXT NOT NULL UNIQUE,
		password_hash TEXT NOT NULL,
		status TEXT NOT NULL,
		balance_cents INTEGER NOT NULL DEFAULT 0,
		flow_quota_mb INTEGER NOT NULL DEFAULT 0,
		traffic_used_bytes INTEGER NOT NULL DEFAULT 0,
		aff_balance_cents INTEGER NOT NULL DEFAULT 0,
		plan_id INTEGER NULL,
		user_group_id INTEGER NULL,
		max_rules INTEGER NOT NULL DEFAULT 0,
		traffic_enable INTEGER NOT NULL DEFAULT 1,
		auto_renew INTEGER NOT NULL DEFAULT 0,
		telegram_id TEXT NOT NULL DEFAULT '',
		invite_code TEXT NOT NULL DEFAULT '',
		invited_by_user_id INTEGER NULL,
		allow_device INTEGER NOT NULL DEFAULT 1,
		notification_settings_json TEXT NULL,
		expires_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS nodes (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL UNIQUE,
		host TEXT NOT NULL,
		port INTEGER NOT NULL,
		secret TEXT NOT NULL,
		status TEXT NOT NULL,
		last_seen_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS tunnels (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		node_id INTEGER NOT NULL,
		name TEXT NOT NULL,
		protocol TEXT NOT NULL,
		listen_addr TEXT NOT NULL,
		target_addr TEXT NOT NULL,
		listen_host TEXT NOT NULL DEFAULT '',
		listen_port INTEGER NULL,
		target_host TEXT NOT NULL DEFAULT '',
		target_port INTEGER NULL,
		device_group_in_id INTEGER NULL,
		device_group_out_id INTEGER NULL,
		config_json TEXT NULL,
		folder TEXT NOT NULL DEFAULT '',
		show_order INTEGER NOT NULL DEFAULT 0,
		max_conn INTEGER NOT NULL DEFAULT 0,
		speed_limit_kb INTEGER NOT NULL DEFAULT 0,
		quota_bytes INTEGER NOT NULL DEFAULT 0,
		used_bytes INTEGER NOT NULL DEFAULT 0,
		expires_at DATETIME NULL,
		auto_pause_on_limit INTEGER NOT NULL DEFAULT 1,
		status TEXT NOT NULL,
		traffic_reset_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(node_id) REFERENCES nodes(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_tunnels_user_id ON tunnels(user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_tunnels_node_id ON tunnels(node_id)`,
	`CREATE TABLE IF NOT EXISTS forward_services (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		tunnel_id INTEGER NOT NULL UNIQUE,
		user_id INTEGER NOT NULL,
		node_id INTEGER NOT NULL,
		service_key TEXT NOT NULL UNIQUE,
		protocol TEXT NOT NULL,
		listen_addr TEXT NOT NULL,
		target_addr TEXT NOT NULL,
		status TEXT NOT NULL,
		max_conn INTEGER NOT NULL DEFAULT 0,
		speed_limit_kb INTEGER NOT NULL DEFAULT 0,
		quota_bytes INTEGER NOT NULL DEFAULT 0,
		used_bytes INTEGER NOT NULL DEFAULT 0,
		bytes_in INTEGER NOT NULL DEFAULT 0,
		bytes_out INTEGER NOT NULL DEFAULT 0,
		active_conn INTEGER NOT NULL DEFAULT 0,
		paused_reason TEXT NOT NULL DEFAULT '',
		config_json TEXT NULL,
		device_group_in_id INTEGER NULL,
		device_group_out_id INTEGER NULL,
		listen_port INTEGER NULL,
		last_report_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		FOREIGN KEY(tunnel_id) REFERENCES tunnels(id) ON DELETE CASCADE,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
		FOREIGN KEY(node_id) REFERENCES nodes(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_forward_services_node_id ON forward_services(node_id)`,
	`CREATE INDEX IF NOT EXISTS idx_forward_services_user_id ON forward_services(user_id)`,
	`CREATE TABLE IF NOT EXISTS payment_channels (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		code TEXT NOT NULL UNIQUE,
		name TEXT NOT NULL,
		enabled INTEGER NOT NULL DEFAULT 1,
		provider TEXT NOT NULL,
		config_json TEXT NOT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS payment_orders (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		order_no TEXT NOT NULL UNIQUE,
		user_id INTEGER NOT NULL,
		channel TEXT NOT NULL,
		amount_cents INTEGER NOT NULL,
		status TEXT NOT NULL,
		pay_url TEXT NOT NULL DEFAULT '',
		trade_no TEXT NOT NULL DEFAULT '',
		raw_request TEXT NOT NULL,
		raw_notify TEXT NOT NULL,
		paid_at DATETIME NULL,
		type TEXT NOT NULL DEFAULT 'deposit',
		plan_id INTEGER NULL,
		quantity INTEGER NOT NULL DEFAULT 1,
		metadata_json TEXT NULL,
		expired_at DATETIME NULL,
		closed_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_payment_orders_user_id ON payment_orders(user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_payment_orders_status ON payment_orders(status)`,
	`CREATE TABLE IF NOT EXISTS sessions (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		actor_kind TEXT NOT NULL,
		actor_id INTEGER NOT NULL,
		token_hash TEXT NOT NULL UNIQUE,
		expires_at DATETIME NOT NULL,
		created_at DATETIME NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_sessions_actor ON sessions(actor_kind, actor_id)`,
	`CREATE TABLE IF NOT EXISTS node_commands (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		node_id INTEGER NOT NULL,
		type TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		status TEXT NOT NULL,
		available_at DATETIME NOT NULL,
		consumed_at DATETIME NULL,
		created_at DATETIME NOT NULL,
		FOREIGN KEY(node_id) REFERENCES nodes(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_node_commands_node_status_id ON node_commands(node_id, status, id)`,
	`CREATE TABLE IF NOT EXISTS usage_reports (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		node_id INTEGER NOT NULL,
		service_key TEXT NOT NULL,
		bytes_in INTEGER NOT NULL,
		bytes_out INTEGER NOT NULL,
		active_conn INTEGER NOT NULL,
		reported_at DATETIME NOT NULL,
		created_at DATETIME NOT NULL,
		FOREIGN KEY(node_id) REFERENCES nodes(id) ON DELETE CASCADE
	)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_reports_node_id ON usage_reports(node_id)`,
	`CREATE INDEX IF NOT EXISTS idx_usage_reports_service_key ON usage_reports(service_key)`,
	`CREATE TABLE IF NOT EXISTS audit_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		actor_kind TEXT NOT NULL,
		actor_id INTEGER NOT NULL,
		action TEXT NOT NULL,
		target_kind TEXT NOT NULL,
		target_id INTEGER NOT NULL DEFAULT 0,
		detail_json TEXT NOT NULL,
		created_at DATETIME NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_logs_actor ON audit_logs(actor_kind, actor_id)`,
	`CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action)`,
	`CREATE TABLE IF NOT EXISTS schema_migrations (
		version TEXT PRIMARY KEY,
		description TEXT NOT NULL,
		applied_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS device_groups (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		type TEXT NOT NULL DEFAULT 'node',
		node_id INTEGER NULL,
		ratio REAL NOT NULL DEFAULT 1.0,
		connect_host TEXT NOT NULL DEFAULT '',
		port_range_start INTEGER NULL,
		port_range_end INTEGER NULL,
		config_json TEXT NULL,
		show_order INTEGER NOT NULL DEFAULT 0,
		display_num INTEGER NOT NULL DEFAULT 0,
		hide_status INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'enabled',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		deleted_at DATETIME NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_device_groups_type ON device_groups(type)`,
	`CREATE INDEX IF NOT EXISTS idx_device_groups_node_id ON device_groups(node_id)`,
	`CREATE INDEX IF NOT EXISTS idx_device_groups_status ON device_groups(status)`,
	`CREATE TABLE IF NOT EXISTS plans (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		description TEXT NULL,
		price_cents INTEGER NOT NULL DEFAULT 0,
		traffic_mb INTEGER NOT NULL DEFAULT 0,
		duration_days INTEGER NOT NULL DEFAULT 0,
		max_rules INTEGER NOT NULL DEFAULT 0,
		allow_device INTEGER NOT NULL DEFAULT 1,
		user_group_id INTEGER NULL,
		status TEXT NOT NULL DEFAULT 'enabled',
		show_order INTEGER NOT NULL DEFAULT 0,
		config_json TEXT NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL,
		deleted_at DATETIME NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_plans_status ON plans(status)`,
	`CREATE INDEX IF NOT EXISTS idx_plans_show_order ON plans(show_order)`,
	`CREATE TABLE IF NOT EXISTS user_groups (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		name TEXT NOT NULL,
		description TEXT NULL,
		max_rules INTEGER NOT NULL DEFAULT 0,
		traffic_multiplier REAL NOT NULL DEFAULT 1.0,
		permissions_json TEXT NULL,
		show_order INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'enabled',
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_user_groups_status ON user_groups(status)`,
	`CREATE TABLE IF NOT EXISTS redeem_codes (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		code TEXT NOT NULL UNIQUE,
		type TEXT NOT NULL DEFAULT 'balance',
		amount_cents INTEGER NOT NULL DEFAULT 0,
		plan_id INTEGER NULL,
		traffic_mb INTEGER NOT NULL DEFAULT 0,
		duration_days INTEGER NOT NULL DEFAULT 0,
		max_use INTEGER NOT NULL DEFAULT 1,
		used_count INTEGER NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'enabled',
		expires_at DATETIME NULL,
		created_by_admin_id INTEGER NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_redeem_codes_status ON redeem_codes(status)`,
	`CREATE TABLE IF NOT EXISTS redeem_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		redeem_code_id INTEGER NOT NULL,
		user_id INTEGER NOT NULL,
		order_id INTEGER NULL,
		created_at DATETIME NOT NULL,
		UNIQUE(redeem_code_id, user_id)
	)`,
	`CREATE TABLE IF NOT EXISTS aff_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NOT NULL,
		from_user_id INTEGER NULL,
		order_id INTEGER NULL,
		type TEXT NOT NULL,
		amount_cents INTEGER NOT NULL DEFAULT 0,
		rate REAL NOT NULL DEFAULT 0,
		status TEXT NOT NULL DEFAULT 'pending',
		detail_json TEXT NULL,
		created_at DATETIME NOT NULL,
		accounted_at DATETIME NULL
	)`,
	`CREATE INDEX IF NOT EXISTS idx_aff_logs_user_id ON aff_logs(user_id)`,
	`CREATE INDEX IF NOT EXISTS idx_aff_logs_status ON aff_logs(status)`,
	`CREATE TABLE IF NOT EXISTS system_kv (
		key_name TEXT PRIMARY KEY,
		value_json TEXT NULL,
		value_text TEXT NULL,
		scope TEXT NOT NULL DEFAULT 'global',
		updated_by_admin_id INTEGER NULL,
		created_at DATETIME NOT NULL,
		updated_at DATETIME NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS notification_logs (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		user_id INTEGER NULL,
		channel TEXT NOT NULL,
		type TEXT NOT NULL,
		title TEXT NOT NULL DEFAULT '',
		content TEXT NULL,
		status TEXT NOT NULL DEFAULT 'pending',
		raw_response TEXT NULL,
		created_at DATETIME NOT NULL,
		sent_at DATETIME NULL
	)`,
	`INSERT OR IGNORE INTO device_groups(name, type, node_id, connect_host, status, created_at, updated_at)
		SELECT name, 'node', id, host, 'enabled', created_at, updated_at FROM nodes`,
}
